services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: eventflow-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
  #KAFKA MESSAGE BROKER
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: eventflow-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092, PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
  #KAFKA UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: eventflow-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTER_0_NAME: eventflow
      KAFKA_CLUSTER_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTER_0_ZOOKEEPER: zookeeper:2181
  
  #postgreSQL DATABASE
  postgres:
    image: postgres:16-alpine
    container_name: evenflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow-password
      POSTGRES_DB: eventflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  #REDIS (for caching/session)
  redis:
    image: redis:7-alpine
    container_name: eventflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  #MAilHog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: eventflow-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    
volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  postgres-data:
  redis-data:





